baseURL = "/"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Side Effect"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
copyright = "2023 Side Effect All rights reserved"

[Author]
  name = "Thibault Wittemberg"
  email = "thibault@sideeffect.io"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = "UA-109460106-1"
  twitter_handle = "@nakodark"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = true
  addDot = true
  addFrame = true
  highlightColor = "#56ADAE" # side effect green
  baseColor = "#FFFFFF"
  baseOffsetColor = "#FFFFFF"
  headingColor = "#373930" # side effect dark gray
  textColor = "#373930" # side effect dark gray
  dotColor = "#56ADAE" # side effect green

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
